# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: 'Build'
  displayName: 'Building the API' 
  jobs:
  - job: Build
    displayName: 'MaerskAPI : Build, Test'
  pool:
    vmImage: 'vs2017-win2016'
    steps:
    - checkout: self
      clean: true
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: Maersk/MaerskAPI.csproj
        selectOrConfig: config
        nugetConfigPath: Nuget.config
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: Maersk/MaerskAPI.csproj
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: Maersk/MaerskAPI.csproj
        arguments: --configuration $(BuildConfiguration) --collect "Code coverage"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: 'Docker_Build'
  displayName: 'Building DockerFile'
  dependsOn: Build
  jobs:
  - job: DockerBuild
    displayName: 'MaerskAPI : Build & Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true
    - task: Docker@2
      displayName: Build the docker file
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'MaerskAPI.$(Build.BuildId)'
        containerRegistry: 'Azure Subscription'
        repository: 'MaerskAPI'
    - task: Docker@2
      displayName: Push the docker file to ACR
      inputs:
        command: 'push'
        Dockerfile: '**/Dockerfile'
        tags: 'MaerskAPI.$(Build.BuildId)'
        containerRegistry: 'Azure Subscription'
        repository: 'MaerskAPI'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'Maresk'
        Contents: 'MaerskAPI.yml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

 
    

